Origin/feature/top posts to most commented
pocketnetteam/pocketnet.gui pull request #623
Opened 2022-08-15 15:31 UTC by MoMentalochka

Reopened pull after unwanted pull #582 deletion

2022-09-11 23:30 UTC, MoMentalochka commented
Now in the side menu there are the Best and Discussed feeds, loading with a pagination step of 60 blocks and a maximum depth limit per month (43200 blocks)

2022-09-20 13:51 UTC, maxgithubprofile approved these changes

2022-09-20 14:05 UTC, shpingalet007 requested changes
### Redundant linting in these files
- components/lenta/index.js
- js/satolist.js

### And other issues...

2022-09-20 14:05 UTC, shpingalet007 commented on components/comments/index.js
> +
Redundant linting

2022-09-21 07:29 UTC, maxgithubprofile approved these changes

2022-09-21 07:38 UTC, shpingalet007 approved these changes
Quality checked

2022-09-21 07:46 UTC, merged