patch: remove christmas theme
pocketnetteam/pocketnet.gui pull request #879
Opened 2023-01-20 15:45 UTC by j-bitmaker

## Standards checklist:

- [x] The PR title is descriptive.
- [x] The PR doesn't replicate another PR which is already open.
- [x] The PR has self-explained commits history.

- [x] The code is mine or it's from somewhere with an Apache-2.0 compatible license.
- [x] The code is efficient, to the best of my ability, and does not waste computer resources.
- [x] The code is stable and I have tested it myself, to the best of my abilities.
- [x] If the code introduces new classes, methods, I provide a valid use case for all of them.

## Changes:

- [...]

## Other comments:

This PR is closed #878

2023-01-21 16:49 UTC, shpingalet007 requested changes
I think we need to make some flag for next year. It will permit us to put the Christmas theme without doing the same work next year

2023-01-23 10:25 UTC, j-bitmaker commented
@shpingalet007 I think it will not big problem to return quickly all icons - I have returned all styles of christmas themes, which will not conflict with not-christmas code. Thus, in next year we need only return pathes of images to certain icons.

2023-01-24 07:04 UTC, maxgithubprofile approved these changes

2023-01-24 08:40 UTC, shpingalet007 approved these changes
Quality checked.

I hope next time, @j-bitmaker, we'll be able to do better mechanics for theme support...

2023-01-24 09:11 UTC, merged