patch: calls ui update
pocketnetteam/pocketnet.gui pull request #924
Opened 2023-02-13 02:33 UTC by MoMentalochka

2023-02-13 06:52 UTC, maxgithubprofile approved these changes

2023-02-13 12:22 UTC, shpingalet007 requested changes
### Next things need to be resolved
- No checklist in PR
- Can't check minified code, consider attach SHA of commit from where the build of calls repository was done

2023-02-14 08:44 UTC, maxgithubprofile approved these changes

2023-02-14 08:48 UTC, shpingalet007 approved these changes
Quality checked

2023-02-14 08:53 UTC, merged